<a href="https://colab.research.google.com/github/Aj-pete/Lab-agile-planning/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [4]:
%%sql
select table_name
from information_schema.tables
where table_schema= 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [21]:
%%sql
SELECT * FROM sales
order by customerkey desc
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,2964016,0,2023-02-11,2023-02-11,2099743,540,37,2,299.23,299.23,99.14,USD,1.00
1,2633018,1,2022-03-17,2022-03-17,2099743,610,184,1,94.05,94.05,43.25,USD,1.00
2,2633018,0,2022-03-17,2022-03-17,2099743,610,898,6,62.59,62.59,31.92,USD,1.00
3,591007,0,2016-08-13,2016-08-18,2099711,999999,455,1,2297.50,2067.75,761.20,USD,1.00
4,957007,0,2017-08-14,2017-08-14,2099711,670,425,6,738.00,656.82,376.26,USD,1.00
5,2813044,2,2022-09-13,2022-09-14,2099697,999999,2506,1,4.74,4.74,2.42,USD,1.00
6,2813044,0,2022-09-13,2022-09-14,2099697,999999,1669,1,6.89,6.82,3.17,USD,1.00
7,2813044,1,2022-09-13,2022-09-14,2099697,999999,1694,3,8.88,8.88,4.08,USD,1.00
8,3218016,1,2023-10-23,2023-10-23,2099656,540,1582,4,17.99,17.99,8.27,USD,1.00
9,3218016,2,2023-10-23,2023-10-23,2099656,540,1498,6,300.00,300.00,137.96,USD,1.00

In [20]:
%%sql
select *
from customer
order by customerkey desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,2099743,591,1985-04-01,2045-12-25,North America,female,Ms.,Luciana,N,Almonte,...,39095,US,United States,2000-02-22,21,Cabinetmaker,Frank's Nursery & Crafts,1995 Subaru Vivio,33.06,-90.02
1,2099711,591,1980-08-26,2043-04-27,North America,female,Mrs.,Katerina,M,Pavlícková,...,39401,US,United States,1941-01-01,80,Light truck driver,Lawnscape Garden Maintenance,2006 Bentley Arnage,31.26,-89.19
2,2099697,570,2003-03-17,2043-03-02,North America,male,Mr.,Phillipp,S,Maier,...,93401,US,United States,1966-12-08,54,Mail sorter,Excella,2010 Subaru Tribeca,35.23,-120.59
3,2099656,567,1997-04-07,2043-01-10,North America,male,Mr.,Wilfredo,A,Lozada,...,35404,US,United States,1945-08-24,75,Industrial economist,Williams Bros.,2012 Mercedes-Benz E,33.17,-87.51
4,2099639,580,1988-12-05,2016-07-02,North America,male,Mr.,Miroslav,M,Slach,...,62550,US,United States,1945-04-30,75,Placement specialist,Strength Gurus,2006 Suzuki Sea Forenza Wagon,39.59,-88.89
5,2099619,580,1983-05-20,2042-05-02,North America,female,Ms.,Marthe,T,Fredriksen,...,63101,US,United States,1967-10-21,53,Metal caster,Brendle's,2011 Cadillac CTS,38.57,-90.10
6,2099608,604,1991-05-27,2026-09-07,North America,female,Ms.,Katerina,A,Ríhová,...,16803,US,United States,1984-01-09,37,Personal and home care aide,Komerci,1997 Oldsmobile Achieva,40.73,-77.98
7,2099603,584,2010-07-12,2043-07-02,North America,female,Mrs.,Milly,O,Holm,...,70171,US,United States,1981-08-12,39,Strength trainer,Access Asia,2003 Chevrolet SSR,29.93,-90.05
8,2099574,582,1993-03-22,2007-12-01,North America,male,Mr.,August,A,Akhtar,...,67642,US,United States,1948-07-26,72,Administrative office assistant,Nedick's,2011 Audi A8,39.34,-99.91
9,2099549,614,1999-07-13,2045-12-20,North America,female,Ms.,Indiana,R,Ortiz,...,53188,US,United States,1951-07-28,69,Oral pathologist,Formula Gray,1999 Isuzu VehiCross,43.07,-88.27

In [8]:
%%sql
select *
from product
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
5,6,101006,Contoso 2G MP3 Player E200 Black,"Contoso, Ltd",Contoso,Black,ounces,8.80,11.00,21.57,1,Audio,101,MP4&MP3
6,7,101007,Contoso 2G MP3 Player E200 Blue,"Contoso, Ltd",Contoso,Blue,ounces,2.10,11.00,21.57,1,Audio,101,MP4&MP3
7,8,101008,Contoso 4G MP3 Player E400 Silver,"Contoso, Ltd",Contoso,Silver,ounces,5.60,30.58,59.99,1,Audio,101,MP4&MP3
8,9,101009,Contoso 4G MP3 Player E400 Black,"Contoso, Ltd",Contoso,Black,ounces,2.10,30.58,59.99,1,Audio,101,MP4&MP3
9,10,101010,Contoso 4G MP3 Player E400 Green,"Contoso, Ltd",Contoso,Green,ounces,11.00,30.58,59.99,1,Audio,101,MP4&MP3

In [6]:
%%sql
select *
from date
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1
3,2015-01-04,20150104,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Sunday,Sun,1,0,1
4,2015-01-05,20150105,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Monday,Mon,2,1,2
5,2015-01-06,20150106,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Tuesday,Tue,3,1,3
6,2015-01-07,20150107,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Wednesday,Wed,4,1,4
7,2015-01-08,20150108,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,1,5
8,2015-01-09,20150109,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,6
9,2015-01-10,20150110,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,6

In [9]:
%%sql
select *
from store
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured
3,35,3,5,AU,Australia,South Australia,2015-12-08,None,Contoso Store South Australia,3000.00,None
4,40,4,6,AU,Australia,Tasmania,2010-01-01,None,Contoso Store Tasmania,2000.00,None
5,50,5,7,AU,Australia,Victoria,2015-12-09,None,Contoso Store Victoria,2000.00,None
6,60,6,8,AU,Australia,Western Australia,2010-01-01,None,Contoso Store Western Australia,2000.00,None
7,70,7,12,CA,Canada,New Brunswick,2007-05-07,2014-03-09,Contoso Store New Brunswick,1105.00,Restructured
8,72,7,12,CA,Canada,New Brunswick,2015-01-11,2018-02-02,Contoso Store New Brunswick,1500.00,Restructured
9,74,7,12,CA,Canada,New Brunswick,2018-06-02,None,Contoso Store New Brunswick,3500.00,None

In [10]:
%%sql
--revenue grouping
select s.orderdate, s.quantity *s.netprice * s.exchangerate AS net_revenue,
c.givenname, c.surname, c.countryfull, c.continent,
p.productkey,
p.productname,
p.categoryname, p.subcategoryname,
case when s.quantity *s.netprice * s.exchangerate > 1000 then 'high' else 'low' end as high_low
FROM
sales s
left join customer c on s.customerkey = c.customerkey
left join product p on s.productkey = p.productkey
where
orderdate::date >= '2020-01-01'
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,99.47,Heike,Burger,Germany,Europe,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,low
1,2020-01-01,139.97,Heike,Burger,Germany,Europe,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,low
2,2020-01-01,669.39,Heike,Burger,Germany,Europe,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",low
3,2020-01-01,4090.60,Heike,Burger,Germany,Europe,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,high
4,2020-01-01,237.15,Michelle,Seeber,Canada,North America,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,low
5,2020-01-01,1507.16,Jason,Smith,United States,North America,2061,Contoso Microwave 1.5CuFt X0110 Silver,Home Appliances,Microwaves,high
6,2020-01-01,189.35,Jason,Smith,United States,North America,1717,MGS Flight Simulator X M250,Games and Toys,Download Games,low
7,2020-01-01,539.90,Jason,Smith,United States,North America,435,Adventure Works Desktop PC1.60 ED160 White,Computers,Desktops,low
8,2020-01-01,5590.00,James,Frye,United States,North America,451,WWI Desktop PC2.30 M2300 Silver,Computers,Desktops,high
9,2020-01-01,3580.00,Johnny,Couch,United States,North America,535,WWI LCD19W M100 White,Computers,Monitors,high

In [15]:
%%sql
--total customers per day in 2023

select
COUNT(distinct customerkey),
orderdate
from sales
where orderdate between '2023-01-01' and '2023-12-31'
group by orderdate
order by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

     count   orderdate
0       12  2023-01-01
1       49  2023-01-02
2       64  2023-01-03
3       78  2023-01-04
4       87  2023-01-05
..     ...         ...
359     73  2023-12-27
360     75  2023-12-28
361     55  2023-12-29
362     91  2023-12-30
363      9  2023-12-31

[364 rows x 2 columns]

In [27]:
%%sql
--daily customers 2023 broken down by region
select orderdate, COUNT(distinct s.customerkey), continent
from sales s
left join customer c on s.customerkey = c.customerkey
where orderdate between '2023-01-01' and '2023-12-31'
group by orderdate, continent;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1026 rows affected.

       orderdate  count      continent
0     2023-01-01      1      Australia
1     2023-01-01      6         Europe
2     2023-01-01      5  North America
3     2023-01-02      3      Australia
4     2023-01-02     15         Europe
...          ...    ...            ...
1021  2023-12-30     16      Australia
1022  2023-12-30     25         Europe
1023  2023-12-30     50  North America
1024  2023-12-31      1         Europe
1025  2023-12-31      8  North America

[1026 rows x 3 columns]

In [28]:
%%sql
--pivot with count(using case statement); find daily customers 2023 broken down by region)
select s.orderdate,
COUNT(DISTINCT s.customerkey) as total_customers,
COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) as eu_customers,
COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) as na_customers,
COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END) as as_customers
from
sales s
left join customer c on s.customerkey = c.customerkey
where orderdates.quantity *s.netprice * s.exchangerate
group by orderdate
order by orderdate;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_customers  na_customers  as_customers
0    2023-01-01               12             6             5             1
1    2023-01-02               49            15            31             3
2    2023-01-03               64            17            44             3
3    2023-01-04               78            28            46             4
4    2023-01-05               87            22            57             8
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26            41             6
360  2023-12-28               75            24            44             7
361  2023-12-29               55            19            32             4
362  2023-12-30               91            25            50            16
363  2023-12-31                9             1             8             0

[364 rows x 5 columns]

In [34]:
%%sql
--pivoting with sum ; find total revenue 2022 vs 2023 by category
select
p.categoryname,
SUM(s.quantity *s.netprice * s.exchangerate) AS net_rev,
SUM(CASE WHEN s.orderdate between '2022-01-01' and '2022-12-31' THEN s.quantity *s.netprice * s.exchangerate ELSE 0 END) AS netrev_2022,
SUM(CASE WHEN s.orderdate between '2023-01-01' and '2023-12-31' THEN s.quantity *s.netprice * s.exchangerate ELSE 0 END) AS netrev_2023
FROM sales s
LEFT JOIN product p on s.productkey = p.productkey
GROUP BY
p.categoryname
order by
categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname     net_rev  netrev_2022  netrev_2023
0                          Audio  5312898.10    766938.21    688690.18
1        Cameras and camcorders  18520360.66   2382532.56   1983546.29
2                    Cell phones 32624265.72   8119665.07   6002147.63
3                      Computers 90619022.05  17862213.49  11650867.21
4                 Games and Toys  1668574.13    316127.30    270374.96
5                Home Appliances 26607245.54   6612446.68   5919992.87
6  Music, Movies and Audio Books 10588311.00   2989297.28   2180768.13
7                   TV and Video 20466861.38   5815336.61   4412178.23

In [18]:
%%sql
--pivoting with median--use percentile_cont(0.5) within GROUP (order by column_name) as median
select
PERCENTILE_CONT(0.5) within group(order by netprice) as median_price
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [15]:
%%sql
--find median sales by categroy for 2022 n 2023
select categoryname,
percentile_cont(0.5) within group(order by(case when orderdate between '2022-01-01' and '2022-12-31'then  (s.quantity *s.netprice * s.exchangerate) end)) as median_sales22,
percentile_cont(0.5) within group(order by(case when orderdate between '2023-01-01' and '2023-12-31'then  (s.quantity *s.netprice * s.exchangerate) end)) as median_sales23
from sales s
left join product p on s.productkey = p.productkey
group by  p.categoryname
order by p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  median_sales22  median_sales23
0                          Audio          257.21          266.59
1        Cameras and camcorders           651.46          672.60
2                    Cell phones          418.60          375.88
3                      Computers          809.70          657.18
4                 Games and Toys           33.78           32.62
5                Home Appliances          791.00          825.25
6  Music, Movies and Audio Books          186.58          159.63
7                   TV and Video          730.46          790.79

In [17]:
%%sql
--using and in a case when condition
--categorise quantity >= 2 and netprice >= 100 then 'multiple high value order'
--quantity >= 2 then 'multiple standard item'
--etprice >= 100 then 'single high value order'
--'single standard item'

select orderdate, quantity, netprice,
case
when quantity >= 2 and netprice >= 100 then 'multiple high value order'
when quantity >= 2 then 'multiple standard item'
when netprice >= 100 then 'single high value order'
else 'single standard item'
end as order_type
from sales
limit  10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       single standard item
1  2015-01-01         1    659.78    single high value order
2  2015-01-01         2     54.38     multiple standard item
3  2015-01-01         4    286.69  multiple high value order
4  2015-01-01         7    135.75  multiple high value order
5  2015-01-01         3    434.30  multiple high value order
6  2015-01-01         1     58.73       single standard item
7  2015-01-01         3     74.99     multiple standard item
8  2015-01-01         2    113.57  multiple high value order
9  2015-01-01         1    499.45    single high value order

In [21]:
%%sql
--using and for multiple conditions;segmenting total rev by median for year 2022 and 2023
select
PERCENTILE_CONT(0.5) within group(order by (s.quantity *s.netprice * s.exchangerate )) as median_rev2223
from sales s
where orderdate between '2022-01-01' and '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_rev2223
0          398.00

In [22]:
%%sql
--continuation after finding median rev for both years or you put median rev inside cte
select p.Categoryname,
SUM(CASE WHEN (s.quantity *s.netprice * s.exchangerate) < 398 AND orderdate between '2022-01-01' and '2022-12-31' THEN (s.quantity *s.netprice * s.exchangerate) END) AS low_rev22,
SUM(CASE WHEN (s.quantity *s.netprice * s.exchangerate) >= 398 AND orderdate between '2022-01-01' and '2022-12-31' THEN (s.quantity *s.netprice * s.exchangerate) END) AS high_rev22,
SUM(CASE WHEN (s.quantity *s.netprice * s.exchangerate) < 398 AND orderdate between '2023-01-01' and '2023-12-31' THEN (s.quantity *s.netprice * s.exchangerate) END) AS low_rev23,
SUM(CASE WHEN (s.quantity *s.netprice * s.exchangerate) >= 398 AND orderdate between '2023-01-01' and '2023-12-31' THEN (s.quantity *s.netprice * s.exchangerate) END) AS high_rev23
FROM sales s
LEFT JOIN product p on s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  low_rev22  high_rev22  low_rev23  high_rev23
0                          Audio  222337.83   544600.39  180251.13   508439.06
1        Cameras and camcorders   133004.54  2249528.02  104869.46  1878676.83
2                    Cell phones  814449.53  7305215.55  729699.39  5272448.24
3                      Computers  624340.42 17237873.07  590790.31 11060076.90
4                 Games and Toys  231979.63    84147.67  206103.36    64271.60
5                Home Appliances  219797.07  6392649.61  176261.35  5743731.52
6  Music, Movies and Audio Books  685808.49  2303488.80  574958.76  1605809.37
7                   TV and Video  272338.29  5542998.32  164275.35  4247902.87

In [27]:
%%sql
-- break down revenue into diff tiers. instead of looking at order low or high than median vlue instead look at where they fall based on percentile

WITH percentile_rev AS (select
PERCENTILE_CONT(0.25) within group(order by (s.quantity *s.netprice * s.exchangerate )) as rev_25th,
PERCENTILE_CONT(0.75) within group(order by (s.quantity *s.netprice * s.exchangerate )) as rev_75th
from sales s
where orderdate between '2022-01-01' and '2023-12-31')

select p.categoryname,
CASE WHEN (s.quantity *s.netprice * s.exchangerate) < rev_25th THEN 'low'
WHEN (s.quantity *s.netprice * s.exchangerate) BETWEEN rev_25th AND rev_75th THEN 'medium'
WHEN (s.quantity *s.netprice * s.exchangerate) > rev_75th THEN 'high'
END AS rev_tier,
sum(s.quantity *s.netprice * s.exchangerate) AS rev
FROM sales s
LEFT JOIN product p on s.productkey = p.productkey
CROSS JOIN percentile_rev
GROUP BY p.categoryname, rev_tier

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                     categoryname rev_tier         rev
0                           Audio     high  1213265.71
1                           Audio      low   267217.01
2                           Audio   medium  3832415.38
3         Cameras and camcorders      high 15050781.63
4         Cameras and camcorders       low    81032.92
5         Cameras and camcorders    medium  3388546.10
6                     Cell phones     high 21874993.15
7                     Cell phones      low   410309.35
8                     Cell phones   medium 10338963.22
9                       Computers     high 79607760.89
10                      Computers      low   203207.06
11                      Computers   medium 10808054.11
12                 Games and Toys     high   133749.09
13                 Games and Toys      low   533443.13
14                 Games and Toys   medium  1001381.91
15                Home Appliances     high 22383475.30
16                Home Appliances      low   105045.60
17                Home Appliances   medium  4118724.64
18  Music, Movies and Audio Books     high  3844996.29
19  Music, Movies and Audio Books      low   642496.71
20  Music, Movies and Audio Books   medium  6100817.99
21                   TV and Video     high 16632856.33
22                   TV and Video      low    67221.76
23                   TV and Video   medium  3766783.30

In [41]:
%%sql
--date_trunc
select
orderdate,
date_trunc('month', orderdate)::date
from sales
order by random()
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  date_trunc
0  2022-09-13  2022-09-01
1  2019-02-05  2019-02-01
2  2022-12-10  2022-12-01
3  2019-03-07  2019-03-01
4  2022-10-20  2022-10-01
5  2023-06-22  2023-06-01
6  2022-01-07  2022-01-01
7  2022-09-27  2022-09-01
8  2016-01-30  2016-01-01
9  2015-05-14  2015-05-01

In [42]:
%%sql
select
date_trunc('month', orderdate)::date as ordermonth,
sum(quantity *netprice * exchangerate) as rev,
count(distinct customerkey) as customers
from sales
group by ordermonth
order by ordermonth

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

     ordermonth        rev  customers
0    2015-01-01  384092.66        200
1    2015-02-01  706374.12        291
2    2015-03-01  332961.59        139
3    2015-04-01  160767.00         78
4    2015-05-01  548632.63        236
..          ...        ...        ...
107  2023-12-01 2928550.93       1484
108  2024-01-01 2677498.55       1340
109  2024-02-01 3542322.55       1718
110  2024-03-01 1692854.89        877
111  2024-04-01  483851.39        246

[112 rows x 3 columns]

In [45]:
%%sql
--TO_CHAR()
select orderdate,
to_char(orderdate, 'YYYY') as year,
to_char(orderdate, 'MM') as month,
to_char(orderdate, 'DD') as day,
to_char(orderdate, 'Day') as day_of_week
from sales
order by random()
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

     orderdate  year month day day_of_week
0   2022-02-14  2022    02  14   Monday
1   2024-03-01  2024    03  01   Friday
2   2023-09-11  2023    09  11   Monday
3   2015-12-29  2015    12  29   Tuesday
4   2020-06-27  2020    06  27   Saturday
5   2022-02-01  2022    02  01   Tuesday
6   2020-03-05  2020    03  05   Thursday
7   2016-10-25  2016    10  25   Tuesday
8   2022-12-26  2022    12  26   Monday
9   2021-11-19  2021    11  19   Friday
10  2023-02-16  2023    02  16   Thursday
11  2022-10-15  2022    10  15   Saturday
12  2022-07-13  2022    07  13   Wednesday
13  2019-02-27  2019    02  27   Wednesday
14  2019-06-11  2019    06  11   Tuesday
15  2022-07-25  2022    07  25   Monday
16  2024-01-06  2024    01  06   Saturday
17  2023-09-18  2023    09  18   Monday
18  2022-02-17  2022    02  17   Thursday
19  2015-01-24  2015    01  24   Saturday

In [47]:
%%sql
select
orderdate,
to_char(orderdate, 'YYYY-MM') as year
from sales
order by random()
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

     orderdate     year
0   2019-07-31  2019-07
1   2019-02-27  2019-02
2   2022-12-09  2022-12
3   2017-08-10  2017-08
4   2019-05-16  2019-05
5   2022-09-09  2022-09
6   2019-03-16  2019-03
7   2023-02-14  2023-02
8   2019-07-03  2019-07
9   2018-02-12  2018-02
10  2019-03-09  2019-03
11  2020-07-17  2020-07
12  2020-10-29  2020-10
13  2018-09-20  2018-09
14  2022-02-16  2022-02
15  2024-02-29  2024-02
16  2016-11-26  2016-11
17  2016-01-21  2016-01
18  2023-05-04  2023-05
19  2018-03-07  2018-03

In [48]:
%%sql
--date_part
select orderdate,
date_part('year', orderdate) as year,
date_part('month', orderdate) as month,
date_part('day', orderdate) as day
from sales
order by random()
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

     orderdate    year  month   day
0   2018-09-25 2018.00   9.00 25.00
1   2021-01-12 2021.00   1.00 12.00
2   2022-12-10 2022.00  12.00 10.00
3   2022-02-10 2022.00   2.00 10.00
4   2018-12-08 2018.00  12.00  8.00
5   2020-02-15 2020.00   2.00 15.00
6   2018-06-11 2018.00   6.00 11.00
7   2019-04-18 2019.00   4.00 18.00
8   2019-05-16 2019.00   5.00 16.00
9   2022-12-02 2022.00  12.00  2.00
10  2015-12-02 2015.00  12.00  2.00
11  2022-03-15 2022.00   3.00 15.00
12  2018-08-03 2018.00   8.00  3.00
13  2021-06-17 2021.00   6.00 17.00
14  2023-12-23 2023.00  12.00 23.00
15  2015-02-28 2015.00   2.00 28.00
16  2023-03-09 2023.00   3.00  9.00
17  2022-03-18 2022.00   3.00 18.00
18  2022-12-24 2022.00  12.00 24.00
19  2018-09-22 2018.00   9.00 22.00

In [54]:
%%sql
--curent date and now()
select now();
select current_date;

select current_date,
extract(year from orderdate) as orderyear,
extract(year from current_date) as currentyear,
extract(year from current_date) -5 as fiveyearsago,
s.orderdate,
p.categoryname,
sum(s.quantity * s.netprice * s.exchangerate) as netrev
from sales s
left join product p on s.productkey = p.productkey
where extract(year from orderdate) >= extract(year from current_date) -5
group by s.orderdate, p.categoryname
order by s.orderdate, p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

1 rows affected.

8957 rows affected.

,current_date,orderyear,currentyear,fiveyearsago,orderdate,categoryname,netrev
0,2026-03-06,2021,2026,2021,2021-01-01,Audio,1206.67
1,2026-03-06,2021,2026,2021,2021-01-01,Cameras and camcorders,2228.75
2,2026-03-06,2021,2026,2021,2021-01-01,Cell phones,10582.00
3,2026-03-06,2021,2026,2021,2021-01-01,Computers,12718.95
4,2026-03-06,2021,2026,2021,2021-01-01,Games and Toys,235.53
...,...,...,...,...,...,...,...
8952,2026-03-06,2024,2026,2021,2024-04-20,Computers,58353.68
8953,2026-03-06,2024,2026,2021,2024-04-20,Games and Toys,1744.30
8954,2026-03-06,2024,2026,2021,2024-04-20,Home Appliances,1562.04
8955,2026-03-06,2024,2026,2021,2024-04-20,"Music, Movies and Audio Books",4949.43
8956,2026-03-06,2024,2026,2021,2024-04-20,TV and Video,9841.91

In [4]:
%%sql
select current_date,
orderdate,
p.categoryname,
sum(s.quantity * s.netprice * s.exchangerate) as netrev
from sales s
left join product p on s.productkey = p.productkey
where
orderdate >= current_date - interval '5 years'
group by s.orderdate, p.categoryname
order by s.orderdate, p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8551 rows affected.

     current_date   orderdate                   categoryname   netrev
0      2026-03-06  2021-03-06                          Audio   442.27
1      2026-03-06  2021-03-06        Cameras and camcorders   6671.44
2      2026-03-06  2021-03-06                    Cell phones  8316.40
3      2026-03-06  2021-03-06                      Computers 22536.20
4      2026-03-06  2021-03-06                 Games and Toys   451.48
...           ...         ...                            ...      ...
8546   2026-03-06  2024-04-20                      Computers 58353.68
8547   2026-03-06  2024-04-20                 Games and Toys  1744.30
8548   2026-03-06  2024-04-20                Home Appliances  1562.04
8549   2026-03-06  2024-04-20  Music, Movies and Audio Books  4949.43
8550   2026-03-06  2024-04-20                   TV and Video  9841.91

[8551 rows x 4 columns]

In [10]:
%%sql
--AGE() AND EXTRACT()
select AGE(current_date, '2023-01-01');
select extract(day from AGE('2023-01-14', '2023-01-08')) - 5;
select age(deliverydate, orderdate)
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

1 rows affected.

199873 rows affected.

          age
0      0 days
1      0 days
2      0 days
3      0 days
4      0 days
...       ...
199868 1 days
199869 1 days
199870 2 days
199871 2 days
199872 2 days

[199873 rows x 1 columns]

In [17]:
%%sql
--find net revenue and average processing time by year(DO FOR THE LAST 5YEARS)
select
to_char(orderdate, 'YYYY') as orderyear,
round(avg(extract(day from age(deliverydate, orderdate))), 2) as processing_time,
cast(sum(quantity *netprice * exchangerate) as integer) as netrev
from sales
where orderdate >= current_date - interval '6 years'
group by orderyear
order by orderyear

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

  orderyear processing_time    netrev
0      2020            0.96   6124259
1      2021            1.36  21357977
2      2022            1.62  44864557
3      2023            1.75  33108566
4      2024            1.67   8396527

In [21]:
%%sql
--WINDOWS FUNCTions; over(),over(partition by)
--find avg revenue by customerkey
select  customerkey,
(quantity * netprice * exchangerate) as netrev,
avg(quantity * netprice * exchangerate) over() as i_avg,
avg(quantity * netprice * exchangerate) over(partition by customerkey) as c_avg
from sales
order by customerkey
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

    customerkey  netrev   i_avg   c_avg
0            15 2217.41 1032.69 2217.41
1           180   71.36 1032.69  836.74
2           180 1913.55 1032.69  836.74
3           180  525.31 1032.69  836.74
4           185 1395.52 1032.69 1395.52
5           243  287.67 1032.69  287.67
6           387  362.44 1032.69  517.32
7           387 1608.10 1032.69  517.32
8           387   30.51 1032.69  517.32
9           387  446.44 1032.69  517.32
10          387  619.77 1032.69  517.32
11          387   97.05 1032.69  517.32
12          387 1265.56 1032.69  517.32
13          387   45.62 1032.69  517.32
14          387  180.35 1032.69  517.32
15          406 1430.73 1032.69 1096.71
16          406  762.69 1032.69 1096.71
17          545   79.67 1032.69  591.91
18          545   66.40 1032.69  591.91
19          545 1344.62 1032.69  591.91

In [30]:
%%sql
--windows function with sum()
--find the percent daily revenue based on order line item. to do this we use window functionnto cal daily revenue. CTEs can be used to solve this too
select
orderdate,
orderkey * 10 + linenumber as orderlinenum,
(quantity * netprice * exchangerate) as netrev,
sum(quantity *netprice* exchangerate) over(partition by orderdate) as totaldailyrev,
(quantity * netprice * exchangerate) * 100 / sum(quantity *netprice* exchangerate) over(partition by orderdate) as pct_of_day
from sales
order by orderdate, pct_of_day desc
limit 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

     orderdate  orderlinenum  netrev  totaldailyrev  pct_of_day
0   2015-01-01         10043 2395.10       11640.80       20.58
1   2015-01-01         10061 1552.32       11640.80       13.34
2   2015-01-01         10022 1302.91       11640.80       11.19
3   2015-01-01         10020 1146.75       11640.80        9.85
4   2015-01-01         10050  975.16       11640.80        8.38
5   2015-01-01         10021  950.25       11640.80        8.16
6   2015-01-01         10041  578.52       11640.80        4.97
7   2015-01-01         10081  574.05       11640.80        4.93
8   2015-01-01         10001  423.28       11640.80        3.64
9   2015-01-01         10040  263.11       11640.80        2.26
10  2015-01-01         10082  262.80       11640.80        2.26
11  2015-01-01         10080  247.97       11640.80        2.13
12  2015-01-01         10030  224.98       11640.80        1.93
13  2015-01-01         10070  142.42       11640.80        1.22
14  2015-01-01         10073  142.42       11640.80        1.22
15  2015-01-01         10010  108.75       11640.80        0.93
16  2015-01-01         10074   67.61       11640.80        0.58
17  2015-01-01         10000   63.49       11640.80        0.55
18  2015-01-01         10060   63.29       11640.80        0.54
19  2015-01-01         10023   58.73       11640.80        0.50